export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST'
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS'
export const ADD_ORDER_FAIL = 'ADD_ORDER_FAIL'

export const REMOVE_ALERT_ORDER = 'REMOVE_ALERT_ORDER'

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL'
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET'

export const GET_CURRENT_USER_ORDERS_REQUEST = 'GET_CURRENT_USER_ORDERS_REQUEST'
export const GET_CURRENT_USER_ORDERS_SUCCESS = 'GET_CURRENT_USER_ORDERS_SUCCESS'
export const GET_CURRENT_USER_ORDERS_FAIL = 'GET_CURRENT_USER_ORDERS_FAIL'
export const GET_CURRENT_USER_ORDERS_RESET = 'GET_CURRENT_USER_ORDERS_RESET'

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL'

export const DELIVER_ORDER_REQUEST = 'DELIVER_ORDER_REQUEST'
export const DELIVER_ORDER_SUCCESS = 'DELIVER_ORDER_SUCCESS'
export const DELIVER_ORDER_FAIL = 'DELIVER_ORDER_FAIL'
export const DELIVER_ORDER_RESET = 'DELIVER_ORDER_RESET'
